nodeLinker: pnp

packageExtensions:
  "@angular-eslint/utils@*":
    dependencies:
      "@typescript-eslint/utils": "*"
      "@typescript-eslint/types": "*"
  "@angular-eslint/eslint-plugin@*":
    dependencies:
      "@typescript-eslint/utils": "*"
      "@typescript-eslint/types": "*"
  "@angular-eslint/eslint-plugin-template@*":
    dependencies:
      "@typescript-eslint/types": "*"
      "@typescript-eslint/utils": "*"
