name: Lint app

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - dev
    paths:
      - 'src/**'
      - '.eslintrc.json'

  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'src/**'
      - '.eslintrc.json'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: ng lint
